version: 2

jobs:
  build:
    xcode:
      version: "8.2"
    steps:
      - checkout
      - run: gem install bundler

  test:
    steps:
      - run: bundle exec fastlane test

  internal_distribution:
    branch: release
    steps:
      - run: bundle exec fastlane deploy

workflows:
  version: 2
  test:
    jobs:
      - build
      - test:
        requires:
          - build

  distribution:
    branch: master
    jobs:
      - trigger:
        type: approval
      - build:
        requires:
          - trigger
      - test:
        requires:
          - build
      - internal_distribution:
        requires:
          - test

  internal_distribution:
    jobs:
      - trigger:
        type: approval
      - build:
        requires:
          - trigger
      - test:
        requires:
          - build
      - internal_distribution:
        requires:
          - test
